name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: tar -cvzf workspace.tar.gz ${{ github.workspace }}
        working-directory: ${{ runner.temp }}
      - uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
  build:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
      - run: tar -xvf ${{ runner.temp }}/workspace.tar.gz
      - run: ls -la
      - run: npm run build
  lint:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
      - run: tar -xvf ${{ runner.temp }}/workspace.tar.gz
      - run: ls -la
      - run: npm run lint
  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
      - run: tar -xvf ${{ runner.temp }}/workspace.tar.gz
      - run: ls -la
      - run: npm run typecheck
  test-unit:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
      - run: tar -xvf ${{ runner.temp }}/workspace.tar.gz
      - run: ls -la
      - run: npm run test:unit
  test-integration:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
      - run: tar -xvf ${{ runner.temp }}/workspace.tar.gz
      - run: ls -la
      - run: npm run test:integration
  commitlint:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
          path: |
            ${{ runner.temp }}/workspace.tar.gz
      - run: tar -xvf ${{ runner.temp }}/workspace.tar.gz
      - run: ls -la
      - run: npm run commitlint -- -f ${{ github.base_ref == '' && github.ref || github.base_ref }}
